#!/bin/bash

# Created by Manik
# on Aug 6, 2020

# Loading config
. config.conf

# Loading artwork
source art.sh

# Define colours
RED='\033[0;31m'
MAGENTA='\033[0;35m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

if [ $TINT == 'Magenta' ]; then
		tint_shade=$MAGENTA
elif [ $TINT == 'Red' ]; then
		echo "lmao"
		tint_shade=$RED
elif [ $TINT == 'Green' ]; then
		tint_shade=$GREEN
elif [ $TINT == 'Yellow' ]; then
		tint_shade=$YELLOW
elif [ $TINT == 'Blue' ]; then
		tint_shade=$BLUE
elif [ $TINT == 'Cyan' ]; then
		tint_shade=$CYAN
else
		tint_shade=$NC
fi

function osname {
	os_t=$(uname -o)
	if [ $os_t == 'GNU/Linux' ]; then
		if [ -f /etc/os-release ]; then
			. /etc/os-release
			echo $NAME $VERSION_ID
		else
			echo "Can't read /etc/os-release"
		fi
	else
		echo "OS family not supported yet"
	fi
}

function total_mem {
	totalk=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
	var=1024
	echo $((totalk/var)) "MiB"
}

function cpu_info {
	cpu=$(lscpu | grep "Model name:" | sed -r 's/Model name:\s{1,}//g')
	echo "$cpu"
}

function wsl_check {
	if grep -q microsoft /proc/version; then
	echo "(WSL)"
	fi
}

function cur_shell {
	curs=$($SHELL --version)
	echo $curs | cut -d' ' -f1-2
}

function up_time {
	uptime -p | cut -d " " -f2- 
}

function totalpackages {
	dpkg-query -f '${binary:Package}\n' -W | wc -l
}

function screenres {
	res=$(timeout 2s bash -c "xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/'")
	if [ -z "$res" ]; then
    	echo "Couldn't find out"
	else
		echo $res
	fi
}






function print_out {

	if [ $ART == 'nfo' ]; then
		printf "$nfo_isometric\n\n"
	elif [ $ART == 'key' ]; then
		printf "$keyboard\n\n"
	elif [ $ART == 'file' ]; then
		printf "$file\n\n"
	elif [ $ART == 'name' ]; then
		printf "$name\n\n"
	elif [ $ART == 'toilet' ]; then
		toilet -f future --gay "$toiet_msg"
	fi

	
	echo -e "${tint_shade}"$USER"${NC}""@""${tint_shade}"$HOSTNAME"${NC}"
	echo -e "${RED}▄${NC} ${MAGENTA}▄${NC} ${YELLOW}▄${NC} ${GREEN}▄${NC} ${CYAN}▄${NC} ${BLUE}▄${NC} "
	echo -e "${RED}▀${NC} ${MAGENTA}▀${NC} ${YELLOW}▀${NC} ${GREEN}▀${NC} ${CYAN}▀${NC} ${BLUE}▀${NC} "
	echo -e "${tint_shade}OS:${NC}		$(osname) $(wsl_check)"
	echo -e "${tint_shade}Resolution:${NC} 	$(screenres)"
	echo -e "${tint_shade}Uptime:${NC}		$(up_time)"
	echo -e "${tint_shade}Shell:${NC}		$(cur_shell)"
	echo -e "${tint_shade}Packages:${NC}	$(totalpackages)"
	echo -e "${tint_shade}Memory:${NC}		$(total_mem)"
	echo -e "${tint_shade}CPU:${NC}		$(cpu_info)"
}

print_out
